<?php

/**
 * Implements hook_block_info()
 */
function ob_blocks_block_info() {
  $blocks = array(
    'ob_create_vent' => array(
      'info' => t('Create Event'),
    ),
  );
  return $blocks;
}

/**
 * Implements hook_block_view()
 */
function ob_blocks_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'ob_create_vent':
      $block['content'] = _ob_blocks_create_event();
    break;
  }
  return $block;
}


function ob_blocks_separate_room($nid){
  $output = '';
  $form = afb_get_add_block(1);
  dpm($form);
  return $output;
}

function _ob_blocks_clear_words($s) {
  $s = ereg_replace("[áàâãª]","a",$s);
  $s = ereg_replace("[ÁÀÂÃ]","A",$s);
  $s = ereg_replace("[éèê]","e",$s);
  $s = ereg_replace("[ÉÈÊ]","E",$s);
  $s = ereg_replace("[íìî]","i",$s);
  $s = ereg_replace("[ÍÌÎ]","I",$s);
  $s = ereg_replace("[óòôõº]","o",$s);
  $s = ereg_replace("[ÓÒÔÕ]","O",$s);
  $s = ereg_replace("[úùû]","u",$s);
  $s = ereg_replace("[ÚÙÛ]","U",$s);
  $s = str_replace(" ","-",$s);
  $s = str_replace("ñ","n",$s);
  $s = str_replace("Ñ","N",$s);
  //para ampliar los caracteres a reemplazar agregar lineas de este tipo:
  //$s = str_replace("caracter-que-queremos-cambiar","caracter-por-el-cual-lo-vamos-a-cambiar",$s);
  $s = str_replace(" ","-",$s);
  return $s;
}





































