<?php

/**
 * Implements hook_block_info()
 */
function ob_blocks_block_info() {
  $blocks = array(
    'ob_create_vent' => array(
      'info' => t('Create Event'),
    ),
  );
  return $blocks;
}

/**
 * Implements hook_block_view()
 */
function ob_blocks_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'ob_create_vent':
      $block['content'] = _ob_blocks_create_event();
    break;
  }
  return $block;
}

function _ob_blocks_create_event(){
  module_load_include('inc', 'node', 'node.pages');
  //$form = node_add('event');
  //dpm($form);
  //$output = drupal_render($form);
  //return $output;
}


function ob_blocks_separate_room($nid){
  $output = '';
  $form = afb_get_add_block(1);
  dpm($form);
  return $output;
}







































