<?php


/**
 * Implements hook_menu().
 */
function ob_wall_menu() {
  $items['admin/config/orbit'] = array(
    'title' => 'Orbit',
    'description' => 'Settings for orbit modules.',
    'position' => 'left',
    'weight' => -10,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  $items['admin/config/orbit/phrase'] = array(
    'title' => 'Phrase Config',
    'description' => 'Configuración de la frase de muro',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ob_wall_phrase'),
    'access arguments' => array('administer site configuration'),
  );

  return $items;
}

/**
 * Implements hook_block_info()
 */
function ob_wall_block_info() {
  $blocks = array(
    'ob_create_post' => array(
      'info' => t('Wall'),
    ),
    'ob_phrase' => array(
      'info' => t('Phrase'),
    ),
    'ob_links' => array(
      'info' => t('Links'),
    ),
  );
  return $blocks;
}

/**
 * Implements hook_block_view()
 */
function ob_wall_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'ob_create_post':
      $block['content'] = drupal_get_form('og_wall_form');
    break;
    case 'ob_phrase':
      $block['content'] = ob_wall_print_phrase();
    break;
     case 'ob_links':
      $block['content'] = ob_wall_print_links();
    break;
  }
  return $block;
}

function og_wall_form($form, &$form_state){
  $form['image'] = array(
    '#title' => t('Imagen'),
    '#type' => 'managed_file',
    '#upload_location' => 'public://wall/',
     '#upload_validators' => array('file_validate_extensions' => array('png gif jpg jpeg')),
  );

  $form['text'] = array(
    '#title' => t('Publicación'),
    '#type' => 'textarea',
  );

  $form['archivo'] = array(
    '#title' => t('Archivo'),
    '#type' => 'managed_file',
    '#upload_location' => 'public://wall/',
     '#upload_validators' => array('file_validate_extensions' => array('pdf doc docx')),
  );

  $options = ob_wall_get_dept('departamento');
  
  $form['permissions'] = array(
    '#type' => 'select',
       '#title' => '',
       '#options' => $options,
  );

  $form['enviar'] =  array(
    '#type' => 'submit',
    '#value' => t('Publicate')
  );

  return $form;
}


function og_wall_form_submit($form, &$form_state){
  $counter = variable_get('ob_wall_counter', 1);
  $counter ++;
 global $user;
  $node = new stdClass();
  $node->type = 'ob_wall';
  $node->title = 'public_' . $counter;
  $node->language = LANGUAGE_NONE;
  $node->uid = $user->uid;
  $node->name = $user->name;
  node_object_prepare($node);
  
  if($form_state['values']['image'] != 0){
    $file = $form['image']['#file'];
    $file->status = 1;
    file_save($file);
    $node->field_imagen['und'][0] = (array) $file;
  }
  

  $node->body['und'][0]['value'] = trim($form['text']['#value']);
  $node->format = 'plain_text';

  if($form_state['values']['archivo'] != 0){
    $archivo = $form['archivo']['#file'];
    $archivo->status = 1;
    $archivo->display = 1;
    file_save($archivo);
    $node->field_archivo['und'][0] = (array) $archivo;
  }

  $permissions = array();
  if ($form_state['values']['permissions'] == 'friend_group') {
  } else {
    $permissions[] = $form_state['values']['permissions'];
  }

  foreach ($permissions as $key => $value) {
    $node->field_permissions['und'][$key]['value'] = $value;
  }
  # code...
  node_save($node);
  variable_set('ob_wall_counter', $counter);
  drupal_set_message(t('Se ha generado la publicación'));
}


function ob_wall_get_dept($machine_name){
  $v = taxonomy_vocabulary_machine_name_load($machine_name);
  $terms = taxonomy_get_tree($v->vid);
  
  $options = array(
    'public' => t('Publico'),
    'friend_group' => t('Grupo de amigos'),
    'specific' => t('Personal'),
  );
  foreach ($terms as $term => $value) {
    $options['term_' . $value->tid] = $value->name;
  }
  return ($options);
}




function ob_wall_tiempo_transcurrido($fecha) {
  if(empty ($fecha)) {
    return "No hay fecha";
  }
 
  $intervalos = array (t("segundo"), t("minuto"), t("hora"), t("dí­a"), t("semana"), t("mes"), t("año"));
  $duraciones = array ("60","60","24","7","4.35","12");
 
  $ahora = time ();
  $Fecha_Unix = $fecha;
 
  if(empty ($Fecha_Unix)) {  
    return t("Fecha incorrecta");
  }

  if($ahora > $Fecha_Unix) {  
    $diferencia     = $ahora - $Fecha_Unix;
    $tiempo         = t("Hace");
  } else {
    $diferencia     = $Fecha_Unix - $ahora;
    $tiempo         = t("Dentro de");
  }
  for($j = 0; $diferencia >= $duraciones[$j] && $j < count ($duraciones)-1; $j++) {
    $diferencia /= $duraciones[$j];
  }
 
  $diferencia = round ($diferencia);
 
  if($diferencia != 1) {
    $intervalos[5].="e"; //meses... la magia del español
    $intervalos[$j].= "s";
  }
 
  return "$tiempo $diferencia $intervalos[$j]";
}


function ob_wall_phrase($form, &$form_state){

  $form['ob_wall_phrase'] = array(
    '#type' => 'textarea',
    '#title' => t('Wall phrase'),
    '#default_value' => variable_get('ob_wall_phrase', ''),
    '#description' => t('Frase a mostrar en el home'),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}


function ob_wall_print_phrase(){
  return variable_get('ob_wall_phrase', '');
}


function ob_wall_print_links(){
  $content = array();

  $content['links_header'] = array(
    '#type' => 'container',
    '#attributes' => array(
      'class' => array(drupal_html_class('ob_header_links')),
    ),
  );

  $content['links_header']['time'] = array(
    '#type' => 'html_tag',
    '#tag' => 'div',
    '#value' => date('g:i a'),
    '#attributes' => array(
      'class' => array(drupal_html_class('ob_time'))
    ),
  );

  $dia = t(date('l'));
  $d_a = t(date('d'));
  $mes = t(date('F'));
  $a_o = t(date('Y'));


  $content['links_header']['date'] = array(
    '#type' => 'html_tag',
    '#tag' => 'div',
    '#value' => $dia . ' ' . $d_a . ' de ' . $mes . ' de ' . $a_o,
    '#attributes' => array(
      'class' => array(drupal_html_class('ob_date'))
    ),
  );


  $content['links_header']['notifications'] = array(
    '#type' => 'container',
    '#attributes' => array(
      'class' => array(drupal_html_class('ob_notifications'))
    ),
  );

  $content['links_header']['profile'] = array(
    '#type' => 'html_tag',
    '#tag' => 'div',
    '#value' => l(t('Profile'),''),
    '#attributes' => array(
      'class' => array(drupal_html_class('ob_profile'))
    ),
  );

  $content['links_header']['logout'] = array(
    '#type' => 'html_tag',
    '#tag' => 'div',
    '#value' => l(t('Logout'),'/user/logout'),
    '#attributes' => array(
      'class' => array(drupal_html_class('ob_logout'))
    ),
  );


  return $content;
}


