<?php
/**
 * @file
 * Polls reports functionality.
 */

/**
 * Implements hook_menu()
 */
function ob_polls_reports_menu() {
  $menu['polls-report'] = array(
    'title' => 'Polls results export',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ob_polls_reports_form'),
    // 'access callback' => '_advpoll_results_access',
    'access arguments' => array('export polls reports'),
    'type' => MENU_CALLBACK,
    'file' => 'ob_polls_reports.pages.inc',
  );
  $menu['poll/%node/results'] = array(
    'title' => 'Results',
    'page callback' => 'ob_polls_reports_results_page',
    'page arguments' => array(1),
    'access arguments' => array('export polls reports'),
    'type' => MENU_CALLBACK,
    'file' => 'ob_polls_reports.pages.inc',
  );
  $menu['poll/%node/results.pdf'] = array(
    'title' => 'Results pdf',
    'page callback' => 'ob_polls_reports_results_page_pdf',
    'page arguments' => array(1),
    'access arguments' => array('export polls reports'),
    'type' => MENU_CALLBACK,
    'file' => 'ob_polls_reports.pages.inc',
  );
  $menu['poll/%node/results.xls'] = array(
    'title' => 'Results excel',
    'page callback' => 'ob_polls_reports_results_page_xls',
    'page arguments' => array(1),
    'access arguments' => array('export polls reports'),
    'type' => MENU_CALLBACK,
    'file' => 'ob_polls_reports.pages.inc',
  );
  return $menu;
}

/**
 * Implements hook_permission().
 */
function ob_polls_reports_permission() {
  return array(
    'export polls reports' => array(
      'title' => t('Export polls reports'),
      'description' => t('Export polls reports'),
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ob_polls_reports_form_advpoll_choice_form_alter(&$form, &$form_state, $form_id){
  $node = $form_state['build_info']['args'][0];
  $field_opinion_question = field_get_items('node', $node, 'field_opinion_question');
  if ($field_opinion_question) {
    $question = $field_opinion_question[0]['value'];
    $form['opinion_question'] = array(
      '#title' => $question,
      '#type' => 'textarea',
    );
    $form['submit']['#weight'] = 10;

    $form['#submit'][] = 'ob_polls_reports_opinion_question_submit';
  }
}

/**
 * Opinion question submit
 */
function ob_polls_reports_opinion_question_submit($form, &$form_state) {
  $choice = '';
  foreach ($form_state['values'] as $key => $value) {
    if (is_numeric($key)) {
      $choice = $value;
    }
  }
  global $user;
  $uid = $user->uid;
  $nid = $form_state['build_info']['args'][0]->nid;
  $answer = $form_state['values']['opinion_question'];
  $record = array(
    'nid' => $nid,
    'uid' => $uid,
    'answer' => $answer,
    'choice' => $choice,
  );
  drupal_write_record('users_polls_opinion_answers', $record);
}

/**
 * Implements hook_views_api().
 */
function ob_polls_reports_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'ob_polls_reports') . '/views',
  );
}